Updated documentation for agent for Fargate
alertlogic/al-agent-container pull request #39
Opened 2022-04-22 18:33 UTC by gabcrawf

I have re-written the instructions which I have attached, changes include:
•	Splitting MDR and Cloud Defender into their own sections
•	Section just for CLI should customer wish to deploy it using that method (currently it is a mash up of console/CLI)
•	Adjusted some wording

2022-04-25 14:31 UTC, akontsevoy requested changes
@gabcrawf You overwrote the wrong file (should have been `fargate/README.md` rather than root `README.md`

2022-04-25 14:50 UTC, akontsevoy commented on fargate/README.md
> +The service tasks will now be updated and the agent will show in the Health section of the Alert Logic portal in due course.
Cloud Defender experience does not have the Health section. Instead, it has Hosts and Sources screens.

2022-04-25 17:29 UTC, akontsevoy approved these changes

2022-04-27 08:42 UTC, neil-greenwood approved these changes

2022-04-27 08:43 UTC, merged